export const virtualHorizonTemplate = '<div id="{{id}}" style="display: block; position:absolute; width:1050px; top:{{top}}px; left:{{left}}px; height:839px; overflow:hidden; border-radius: 8px;">'
+    '<div id="{{id}}-angle" style="position:absolute; width:1054px; height:840px; transform:rotate(0deg)">'
+        '<div class="{{id}}-pitch">'
+            '<div style="position:absolute; width:2108px; left:-527px; top:-2574px; height:3000px; background:linear-gradient(to bottom, #007dca 0%, #1ba2cf 100%); border-radius:4px;"></div>'
+            '<div style="position:absolute; border-top:solid 4px white; width:2108px; left:-527px; top:422px; height:3000px; background:linear-gradient(to bottom, #a15101 0%, #804000 100%); border-radius:4px;"></div>'
+        '</div>'
+        '<div style="position:absolute; width:1050px; height:840px; opacity:0.8;">'
+            '<div style="position:absolute; width:1050px; height:530px; top:192px; overflow:hidden;">'
+                '<div class="{{id}}-pitch" style="top:0px;left:264px;width:520px;position:absolute;font-size:18px; font-weight:bold; color:white;"> <!-- 111, 220, 332, 442 -->'
+                    '<div id="{{id}}-levels" style="position:absolute; top:218px;"></div>'
+                '</div>'
+            '</div>'
+        '</div>'
+        '<object data="{{baseUrl}}svgs/vh-heading.svg" type="image/svg+xml" style="top:154px;left:505px;width:40px;position:absolute;"></object>'
+        '<div id="danti-vh-drag" style="position:absolute;top:177px;left:504px;width:43px;height:10px;border:2px solid white;"></div>'
+    '</div>'
+    '<div style="position:absolute; width:1050px; height:844px;">'
+        '<object data="{{baseUrl}}svgs/vh-ticks.svg" type="image/svg+xml" style="top:126px;left:503px;width:44px;position:absolute;"></object>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(10deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(20deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(30deg);">'
+            '<div style="position:absolute; left:300px; height:40px; top:-20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(45deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(60deg);">'
+            '<div style="position:absolute; left:300px; height:40px; top:-20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(-10deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(-20deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(-30deg);">'
+            '<div style="position:absolute; left:300px; height:40px; top:-20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(-45deg);">'
+            '<div style="position:absolute; left:300px; height:20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<div style="position:absolute;left:223px;top:122px; width:600px; height:600px;transform:rotate(-60deg);">'
+            '<div style="position:absolute; left:300px; height:40px; top:-20px; width:0px; border-left:4px solid white;"></div>'
+        '</div>'
+        '<object data="{{baseUrl}}svgs/vh-ttapes.svg" type="image/svg+xml" style="top:310px;left:354px;width:342px;position:absolute;"></object>'
+    '</div>'
+'</div>';

export const virtualHorizonLevelsTemplate = '{{#each levels}}'
+ '<div style="position:absolute; top:{{top}}px; left:166px; width:188px;">'
+    '<div style="position:absolute; top:0px; width:188px; height:15px; border-bottom:3px solid white;">'
+        '<div style="position:absolute; left:-42px; width:36px; text-align:right;">{{name}}</div>'
+        '<div style="position:absolute; left:195px; width:36px; text-align:left;">{{name}}</div>'
+    '</div>'
+    '<div style="position:absolute; top:25px; left:72px; width:44px; height:15px; border-bottom:3px solid white;"></div>'
+    '<div style="position:absolute; top:50px; left:49px; width:90px; height:15px; border-bottom:3px solid white;"></div>'
+    '<div style="position:absolute; top:80px; left:72px; width:44px; height:15px; border-bottom:3px solid white;"></div>'
+'</div>'
+'{{/each}}';
